#!/usr/bin/env bash
REGISTRY=$1;
TAG=$2;
if [[ $REGISTRY == "" ]]; then
       echoerr "image name is required.";
#elif [ "$REGISTRY" == "" ]; then
#       echo "registry is required.";
fi
# put all images to $IMAGES variable
ARR_IMAGES=();
while [ "$3" != "" ]; do
       IMAGES="$IMAGES $3";
       ARR_IMAGES+=($3)
       shift
done
docker-compose up -d --build $IMAGES;
for SERVICE in ${ARR_IMAGES[@]};
	do
		REGISTRY_WITH_CONTAINER="$REGISTRY/$SERVICE:$TAG";
		IMAGE_ID=$(docker ps -a -q -f name=^\*${SERVICE}\$);
	       	echo "IMAGE_ID: ${IMAGE_ID}"
		if [[ $SERVICE != "nginx" ]]; then
			echo ">> Change CMD to npm run start";
			docker commit -c='CMD ["npm", "run", "start"]' $IMAGE_ID $REGISTRY_WITH_CONTAINER;
		else
			echo ">> no update";
			docker commit  $IMAGE_ID $REGISTRY_WITH_CONTAINER;
		fi
	  docker push $REGISTRY_WITH_CONTAINER;
done
echo "Done Deploying $IMAGES images.";
