#!/bin/bash
IMAGE_NAME=$1;
REGISTRY=$2;
if [ $IMAGE_NAME == "" ]; then
	echo "image name is required.";
elif [ "$REGISTRY" == "" ]; then
	echo "registry is required.";
fi
#while [ "$1" != "" ]; do
#        images="$images $1";
#       echo "params 1 equal {$1}."
#       echo "you now have $# position"
#        shift
#done
sudo docker-compose up -d --build $IMAGE_NAME;
IMAGE_ID=$(sudo docker ps -a -q -f name=^/$IMAGE_NAME$);
sudo docker commit $IMAGE_ID $REGISTRY;
sudo docker push $REGISTRY;
